server:
  port: 8002
    #当前应用名称
spring:
  application:
    name: consumer-feign
    #注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

feign:
  circuitbreaker:
    enabled: true
